UI Rework
AdwCustomizerTeam/AdwCustomizer pull request #95
Opened 2022-08-10 15:40 UTC by 0xMRTT

2022-08-10 17:14 UTC, 0xMRTT commented
![Screenshot from 2022-08-10 19-12-49](https://user-images.githubusercontent.com/105598867/183975197-a710e7af-7a53-4f45-bee5-7aecec2511b2.png)
![Screenshot from 2022-08-10 19-12-54](https://user-images.githubusercontent.com/105598867/183975203-99906e10-2593-4c6d-958e-94e9b62a6094.png)
![Screenshot from 2022-08-10 19-12-58](https://user-images.githubusercontent.com/105598867/183975204-cc7bcea7-1e42-4492-8d43-637890b9ff22.png)
![Screenshot from 2022-08-10 19-13-04](https://user-images.githubusercontent.com/105598867/183975208-53823956-0c03-43b9-aa22-8a0dd68f4101.png)
![Screenshot from 2022-08-10 19-13-17](https://user-images.githubusercontent.com/105598867/183975212-577cdc2e-af9e-4dd9-8df5-8b532c0095b5.png)
![Screenshot from 2022-08-10 19-13-42](https://user-images.githubusercontent.com/105598867/183975213-1da6185b-9e19-4ed4-b24f-ac6028607cb6.png)
![Screenshot from 2022-08-10 19-13-52](https://user-images.githubusercontent.com/105598867/183975214-6bcd86af-b5b4-48fb-8747-8d8db2d3735c.png)

2022-08-10 17:25 UTC, daudix-UFO commented
Things that I noticed is monochrome disk-symbolic and adw-gtk3-warning, is that on purpose?

2022-08-10 17:27 UTC, daudix-UFO commented
And advanced tab don't have icon

![image](https://user-images.githubusercontent.com/77155297/183977558-0fd8320d-6f92-4f66-8dc3-ad365def1bbc.png)

2022-08-10 18:15 UTC, 0xMRTT commented
> And advanced tab don't have icon
> 
> ![image](https://user-images.githubusercontent.com/77155297/183977558-0fd8320d-6f92-4f66-8dc3-ad365def1bbc.png)

I use the integrated icons...

2022-08-10 18:16 UTC, 0xMRTT commented
> Things that I noticed is monochrome disk-symbolic and adw-gtk3-warning, is that on purpose?

It's WIP ...
It's for the integration with plugins

2022-08-11 15:04 UTC, 0xMRTT commented
Just need to finish some little things and after merge this PR.

Should we open an issue in TWIG (https://this week.gnome.org)? 

The welcome screen, preset manager and plugins support will come later.

2022-08-11 15:13 UTC, daudix-UFO commented
I think we can!

2022-08-11 15:14 UTC, 0xMRTT commented
> I think we can!

Join the matrix channel thisweek:gnome.org

2022-08-11 15:14 UTC, daudix-UFO commented
Perhaps we will even have time to be in next TWIG!

2022-08-11 15:17 UTC, 0xMRTT commented
Twig for this week close tomorrow at 20 UTC. So we have 29 hours left 😎

2022-08-11 15:27 UTC, daudix-UFO commented
Maked disscussion about it #102

2022-08-11 17:15 UTC, daudix-UFO commented
Can we move hamburger menu to make it first (like in other apps)?

2022-08-11 17:25 UTC, 0xMRTT commented
Just next to the close button ?

2022-08-11 17:26 UTC, daudix-UFO commented
Yes

2022-08-11 17:28 UTC, 0xMRTT commented
Done

2022-08-11 17:39 UTC, 0xMRTT commented
Finally. UI Rework done. 

Know issues:
- Adwaita Manager can freeze while generating a theme or it's slow. In the next release, there will be an AdwStatusPage showing the progress and the logs

If you found bugs. Comment here!

2022-08-11 17:42 UTC, ArtyIF commented
Any final screenshots of the new interface?

2022-08-11 17:43 UTC, daudix-UFO commented
![image](https://user-images.githubusercontent.com/77155297/184198864-862ef26b-f7a5-46a1-af6d-6dc10c59e254.png)
![image](https://user-images.githubusercontent.com/77155297/184198908-6ffe6616-798f-4a58-8383-3e1c672e2470.png)
![image](https://user-images.githubusercontent.com/77155297/184198941-eeb625c3-ce82-41d5-9c45-56ea1a31c321.png)
![image](https://user-images.githubusercontent.com/77155297/184198998-937a713a-2191-4252-a1ad-1f989bdd5e7b.png)

2022-08-11 17:51 UTC, daudix-UFO approved these changes

2022-08-11 17:51 UTC, daudix-UFO commented on src/window.py
> +        store.append("Automatic")
Maybe just "Auto"?

2022-08-11 17:51 UTC, daudix-UFO commented on com.github.AdwCustomizerTeam.AdwCustomizer.json
> +                    "branch": "next"
Switch back to `main`

2022-08-11 17:51 UTC, ArtyIF commented
Nice. I'd say:
- reverse the order of buttons in the title bar to the right - usually GTK apps put the menu button last
- don't forget to update the potfile - call `./po/update_potfile.sh` from the project's root
- speaking of which, replace `MIT/X11 license` with `GNU General Public License version 3`
- and update [this line](https://github.com/AdwCustomizerTeam/AdwCustomizer/blob/main/src/main.py#L454)

2022-08-11 17:56 UTC, ArtyIF requested changes
- [x] reverse the order of buttons in the title bar to the right - usually GTK apps put the menu button last
- [x] don't forget to update the potfile - call ./po/update_potfile.sh from the project's root
- [ ] speaking of which, replace MIT/X11 license with GNU General Public License version 3
- [x] replace any occurence of MIT or similar (you can open the bottom panel and click on the magnifying glass in GNOME Builder to search in the whole project)

2022-08-11 20:17 UTC, 0xMRTT commented
> - [ ] don't forget to update the potfile - call ./po/update_potfile.sh from the project's root

@daudix-UFO It's maybe why locales doesn.t work

2022-08-11 21:14 UTC, 0xMRTT commented
Started writing the Changelog and release notes. Currently saved as draft. (Go on release tab)

2022-08-11 21:37 UTC, daudix-UFO commented
> Started writing the Changelog and release notes. Currently saved as draft. (Go on release tab)

@0xMRTT Polished a little ;)

2022-08-11 21:42 UTC, daudix-UFO commented
Also, don't forget:

- reverse the order of buttons in the title bar to the right

2022-08-11 21:47 UTC, 0xMRTT commented
It's already done.

The menu button is next to the close button.

2022-08-12 07:27 UTC, ArtyIF commented
Was the potfile and the potfile script updated? I don't see it in any of the commits.

2022-08-12 07:28 UTC, 0xMRTT commented
> Was the potfile and the potfile script updated? I don't see it in any of the commits.

Yes, didn't run yet

2022-08-12 09:59 UTC, 0xMRTT commented
![Screenshot from 2022-08-12 11-58-21](https://user-images.githubusercontent.com/105598867/184331685-8e56fa6e-a844-4104-8652-77a6ed81c650.png)
![Screenshot from 2022-08-12 11-58-34](https://user-images.githubusercontent.com/105598867/184331692-0ebe2197-8e8c-4a63-93f3-cc226f93ada7.png)
![Screenshot from 2022-08-12 11-58-38](https://user-images.githubusercontent.com/105598867/184331694-f3a237fc-4212-4266-bf5b-bbdc00c5b2b1.png)
![Screenshot from 2022-08-12 11-58-44](https://user-images.githubusercontent.com/105598867/184331698-401042d9-14ed-43a0-b1da-78fd5659ba24.png)

2022-08-12 15:32 UTC, 0xMRTT commented
@ArtyIF @daudix-UFO @AndroGR. Can I merge ?

2022-08-12 16:35 UTC, daudix-UFO commented
I think it works good

2022-08-12 16:58 UTC, merged

2022-08-20 00:50 UTC, 0xMRTT commented
@all-contributors please add @0xMRTT for code

2022-08-20 00:50 UTC, 0xMRTT commented
@all-contributors please add @daudix-UFO for design

2022-08-20 00:51 UTC, 0xMRTT commented
@all-contributors please add @daudix-UFO for design